Add image upload setting
bolint/wp-szechenyi2020-infoblokk pull request #13
Opened 2020-10-17 17:49 UTC by FarkasJanos

ref #9

2020-10-25 12:50 UTC, bolint requested changes

2020-10-25 12:50 UTC, bolint commented on admin/class-wp-szechenyi2020-infoblokk-admin.php
> +			__( 'Megjelenített Kép', 'wp-szechenyi2020-infoblokk' ),
Fix typo "Kép"!

2020-10-26 20:11 UTC, bolint approved these changes

2020-10-27 05:38 UTC, FarkasJanos commented
Conflict resolved @bolint

2020-10-28 20:05 UTC, merged